services:
  media-service:
    build: .
    container_name: media_service_app
    ports:
      - "${MEDIA_SERVICE_PORT}:50051"
    environment:
      - GRPC_PORT=${GRPC_PORT}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT} 
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
    depends_on:
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "${MEDIA_SERVICE_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: media_service_minio
    ports:
      - "${MINIO_PORT_1}:9000"
      - "${MINIO_PORT_2}:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server --console-address ":${MINIO_PORT_2}" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_PORT_2}/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  grpcui:
    image: fullstorydev/grpcui:latest
    container_name: media_service_ui
    depends_on:
      media-service:
        condition: service_healthy
    command: ["-plaintext", "media-service:${MEDIA_SERVICE_PORT}"]
    ports:
      - "${GRPCUI_PORT}:8080"
    restart: unless-stopped

volumes:
  minio_data: