services:
  postgres:
    image: postgres:16
    container_name: user_service_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./internal/db/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  user_service:
    build: .
    container_name: user_service_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "${USER_SERVICE_PORT}:50051"
    restart: unless-stopped

  grpcui:
    image: fullstorydev/grpcui:latest
    container_name: user_service_ui
    depends_on:
      - user_service
    command: ["-plaintext", "user_service:50051"]
    ports:
      - "${GRPCUI_PORT}:8080"